version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      # Ajustado para o padrão do Postgres 18+
      - ./.data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d root"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gui@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

