name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest  # Foque no mais recente primeiro

    steps:
    - uses: actions/checkout@v5 # Atualizado para v4

    - name: Set up Docker build
      uses: docker/setup-buildx-action@v4.0.0

    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
      uses: docker/login-action@v4.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        username: torralbo
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.SECRET_DOCKER_HUB }}
          
