name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest  # Foque no mais recente primeiro
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        # 1.17 e 1.18 já estão bem defasadas. Use versões modernas se possível.
        go_version: ['1.23', '>=1.23'] 
    
    steps:
    - uses: actions/checkout@v4 # Atualizado para v4

    - name: Set up Go
      uses: actions/setup-go@latest # Atualizado para v5
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build and Start DB
      run: |
        docker-compose up -d
        # Aguarda o banco de dados estar pronto de fato (10 segundos costumam bastar)
        sleep 10 

    - name: Test
      # O ./... garante que ele compile o pacote inteiro antes de testar
      run: go test -v ./... 
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build
      run: go build -v -o main . # Gera o executável
