name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Versões sugeridas no curso (o 1.21 ajuda na estabilidade)
        go_version: ['1.18', '1.17', '1.21']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      # Removido o hífen para o GitHub moderno reconhecer o comando
      run: docker compose build
      
    - name: Create-DB
      run: docker compose up -d

    # O segredo para não dar 'Connection Refused':
    - name: Wait for DB
      run: sleep 15

    - name: Test
      run: go test -v main_test.go 
      
  build:
    needs: test
    # Removido o ubuntu-18.04 que o GitHub desativou
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
